---
- type: replace
  path: /instance_groups/name=smb-server/persistent_vm_type?
  value: small

- type: replace
  path: /instance_groups/name=smb-server/persistent_disk_type?
  value: 50GB

- type: replace
  path: /instance_groups/name=smb-server/jobs/name=smb-server/properties?/users?
  value:
    user-a: "pass-a"
    user-b: "pass-b"
    user-ab: "pass-ab"
    user-ro: "pass-ro"

# https://www.samba.org/samba/docs/current/man-html/smb.conf.5.html
- type: replace
  path: /instance_groups/name=smb-server/jobs/name=smb-server/properties?/shares?
  value:
     share-a:
       "valid users": "user-a user-ab"
       "read only": "no"
       "hosts allow": "0.0.0.0/0"
     share-b:
       "valid users": "user-b user-ab"
       "read only": "no"
       "hosts allow": "0.0.0.0/0"
     share-ro:
       "valid users": "user-ro"
       "read only": "yes"
       "hosts allow": "0.0.0.0/0"
